# Generated by Django 3.0.2 on 2020-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='sname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
